name: GKE kubectl smoke test (SA JSON)

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: "GCP Project ID"
        required: true
      cluster:
        description: "GKE cluster name"
        required: true
      location:
        description: "Region or zone (e.g., us-central1 or us-central1-a)"
        required: true
      namespace:
        description: "Kubernetes namespace to query"
        required: true
        default: "prod"
      deployment:
        description: "Deployment to restart/scale"
        required: true
        default: "nginx"

jobs:
  kubectl-smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Auth to Google Cloud (JSON key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ github.event.inputs.cluster }}
          location:     ${{ github.event.inputs.location }}
          project_id:   ${{ github.event.inputs.project_id }}

      - name: kubectl get pods / deployments
        run: |
          kubectl get pods -n "${{ github.event.inputs.namespace }}" -o wide || true
          kubectl get deployment -n "${{ github.event.inputs.namespace }}" -o wide || true

      - name: Restart deployment
        run: |
          kubectl -n "${{ github.event.inputs.namespace }}" rollout restart deployment/${{ github.event.inputs.deployment }}
          kubectl -n "${{ github.event.inputs.namespace }}" rollout status deployment/${{ github.event.inputs.deployment }}

      - name: Scale deployment to 3 replicas
        run: |
          kubectl -n "${{ github.event.inputs.namespace }}" scale deployment/${{ github.event.inputs.deployment }} --replicas=3
          kubectl -n "${{ github.event.inputs.namespace }}" get deployment/${{ github.event.inputs.deployment }}
