name: GKE kubectl smoke test (SA JSON)

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: "GCP Project ID"
        required: true
      cluster:
        description: "GKE cluster name"
        required: true
      location:
        description: "Region or zone (e.g., us-central1 or us-central1-a)"
        required: true
      namespace:
        description: "Kubernetes namespace"
        required: true
        default: "prod"
      deployment:
        description: "Deployment name to act on"
        required: true
      replicas:
        description: "Number of replicas (used if action_type=scale)"
        required: false
        default: "3"
      action_type:
        description: "Action to perform: restart or scale"
        required: true
        default: "restart"

jobs:
  kubectl-smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Auth to Google Cloud (JSON key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ github.event.inputs.cluster }}
          location:     ${{ github.event.inputs.location }}
          project_id:   ${{ github.event.inputs.project_id }}

      - name: Show current pods and deployments
        run: |
          kubectl get pods -n "${{ github.event.inputs.namespace }}" -o wide || true
          kubectl get deployment -n "${{ github.event.inputs.namespace }}" -o wide || true

      - name: Restart deployment
        if: ${{ github.event.inputs.action_type == 'restart' }}
        run: |
          NS="${{ github.event.inputs.namespace }}"
          DEP="${{ github.event.inputs.deployment }}"
          echo "Restarting deployment $DEP in namespace $NS"
          kubectl -n "$NS" rollout restart deployment/$DEP
          kubectl -n "$NS" rollout status deployment/$DEP --timeout=5m

      - name: Scale deployment
        if: ${{ github.event.inputs.action_type == 'scale' }}
        run: |
          NS="${{ github.event.inputs.namespace }}"
          DEP="${{ github.event.inputs.deployment }}"
          REPLICAS="${{ github.event.inputs.replicas }}"
          echo "Scaling deployment $DEP in namespace $NS to $REPLICAS replicas"
          kubectl -n "$NS" scale deployment/$DEP --replicas=$REPLICAS
          kubectl -n "$NS" get deployment/$DEP
